Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/test.py", line 29, in test
    return await extension.test()
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/test.py", line 59, in test
    output = await check_output(
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/usr/bin/ctest', '--show-only'] to pass: Cannot create directory /home/kavin/ros2_ws/build/my_cpp_pkg/Testing/Temporary
Cannot create log file: LastTest.log
Errors while running CTest
Output from these tests are in: /home/kavin/ros2_ws/build/my_cpp_pkg/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

